In [ ]:
#to crash colab ram , for larger ram
a = []
while(1):
    a.append('1')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sin, cos, sqrt, atan2, radians

In [ ]:
geo_coord = pd.read_csv('Geo Coordinates.csv') #Manually separated coordinates
power = pd.read_csv('windpower_task0_updated.csv')
turbine= pd.read_csv('windturbines.csv')

In [ ]:
geo_coord.head()

    latitude  longitude
0  55.003349   9.983611
1  55.092211   9.971472
2  55.181087   9.959274
3  55.269980   9.947016
4  55.358888   9.934699

In [ ]:
power.head()

                  Unnamed: 0         SE1         SE2         SE3         SE4
0  2000-01-01 00:00:00+00:00  248.367512  466.054477  764.836097  437.724342
1  2000-01-01 01:00:00+00:00  238.104265  449.537397  656.174814  427.607047
2  2000-01-01 02:00:00+00:00  228.781771  497.112675  588.884484  386.638395
3  2000-01-01 03:00:00+00:00  218.608491  588.583537  536.230328  365.970470
4  2000-01-01 04:00:00+00:00  187.179221  639.385540  477.091549  360.579635

In [ ]:
turbine.head()

   Unnamed: 0 Wind turbine ID  ...  Longitude   Latitude
0           0  1781-V-010-001  ...  14.133793  59.253088
1           1  1785-V-006-001  ...  12.802235  59.380151
2           2  1880-V-020-001  ...  15.075022  59.178468
3           3  2321-V-002-001  ...  13.376852  63.437566
4           4  2321-V-001-001  ...  13.376548  63.436982

[5 rows x 10 columns]

In [ ]:
turbine[['Longitude','Latitude']]

      Longitude   Latitude
0     14.133793  59.253088
1     12.802235  59.380151
2     15.075022  59.178468
3     13.376852  63.437566
4     13.376548  63.436982
...         ...        ...
3999  19.924253  65.212280
4000  19.939618  65.205126
4001  19.926770  65.203975
4002  19.929967  65.207829
4003  19.936901  65.194785

[4004 rows x 2 columns]

In [ ]:
turbine['new_col'] = list(zip(turbine.Longitude, turbine.Latitude))

In [ ]:
turbine.head()

   Unnamed: 0  ...                                   new_col
0           0  ...  (14.133793111295974, 59.253088042386636)
1           1  ...   (12.802235454379547, 59.38015130236439)
2           2  ...   (15.075021627622005, 59.17846847716789)
3           3  ...   (13.376852365949885, 63.43756635671431)
4           4  ...   (13.376547864778216, 63.43698164686333)

[5 rows x 11 columns]

In [ ]:
geo_coord['new_col'] = list(zip(geo_coord.longitude, geo_coord.latitude))

In [ ]:
geo_coord.head()

    latitude  longitude                            new_col
0  55.003349   9.983611         (9.983611302, 55.00334947)
1  55.092211   9.971472          (9.97147191, 55.09221055)
2  55.181087   9.959274  (9.959273742, 55.181087399999996)
3  55.269980   9.947016         (9.947016371, 55.26997984)
4  55.358888   9.934699   (9.934699367999999, 55.35888769)

In [ ]:
def shortest_distance(df_1, df_2):
    # Haversine Formula to find distance between two coordinates
    R = 6373.0
    lat1 = radians(df_1[1])
    lon1 = radians(df_1[0])
    lat2 = radians(df_2[1])
    lon2 = radians(df_2[0])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    s.append(distance)
    

m= []

for df_1 in turbine.new_col:
    s=[]
    for values in geo_coord.new_col:
        shortest_distance(df_1,values)
    m.append(s.index(min(s)))
coor= [geo_coord.new_col[co] for co in m] #coordinates of NWP data to be used against each turbine

In [ ]:
coordinates= coor
coordinates

[(14.07930588, 59.22813565),
 (12.84024943, 59.39255071),
 (15.13147047, 59.14169787),
 (13.34048466, 63.44610374),
 (13.34048466, 63.44610374),
 (19.18309021, 63.48488565),
 (12.66099366, 56.96791518),
 (11.60836929, 57.65941794),
 (13.23428746, 55.36926346),
 (18.82986664, 57.82570208),
 (13.58785502, 58.41605608),
 (13.33427487, 56.6214723),
 (13.21688093, 55.72603494),
 (13.21688093, 55.72603494),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (13.05845329, 55.72345025),
 (18.47570761, 57.65701394),
 (18.25764726, 57.12528137),
 (13.59904264, 58.14719419),
 (18.95640653, 57.46269714),
 (12.33303168, 56.96095237),
 (12.33303168, 56.96095237),
 (12.73243384, 58.40323137),
 (13.37533023, 55.72839979),
 (13.21688093, 55.72603494),
 (16.4333538, 56.8929157),
 (13.21688093, 55.72603494),
 (12.53520903, 58.75839712),
 (11.3751847, 58.28082176),
 (11.72442729, 58.20092721),
 (15.13182914, 59.23143862),
 (13.01940768, 56.43768387),
 (17.25453734, 59.48071344),
 (18.4666868, 57.56758803),
 (18.59607092, 57.20511401),
 (18.59607092, 57.20511401),
 (13.23428746, 55.36926346),
 (14.32967864, 55.55948943),
 (12.39739557, 58.30685634),
 (14.32967864, 55.55948943),
 (14.32967864, 55.55948943),
 (18.24932033, 57.03591504),
 (18.24932033, 57.03591504),
 (13.23428746, 55.36926346),
 (15.29989478, 58.4238106),
 (13.01441632, 56.52702944),
 (18.59607092, 57.20511401),
 (12.40428147, 58.21728958),
 (11.39429547, 58.10184255),
 (13.01940768, 56.43768387),
 (13.92445372, 58.59882894),
 (18.24932033, 57.03591504),
 (18.24932033, 57.03591504),
 (13.01441632, 56.52702944),
 (12.90346355, 58.40627311),
 (18.48477544, 57.74645121),
 (12.73243384, 58.40323137),
 (13.00939974, 56.61638916),
 (12.33303168, 56.96095237),
 (13.21247556, 55.8152677),
 (12.89486212, 55.80986429),
 (11.58168223, 57.92778293),
 (18.42227547, 57.12063552),
 (18.42227547, 57.12063552),
 (18.11694324, 57.39790804),
 (18.67150542, 57.9203634),
 (16.9116605, 59.66598966),
 (16.4153324, 56.44593652),
 (13.03797433, 59.03663606),
 (11.36555324, 58.370326299999995),
 (14.78621707, 58.4239907),
 (11.90251948, 58.11584961),
 (11.3751847, 58.28082176),
 (12.6962644, 56.43172994),
 (12.6962644, 56.43172994),
 (11.36555324, 58.370326299999995),
 (13.01940768, 56.43768387),
 (18.09297631, 57.12969841),
 (18.09297631, 57.12969841),
 (12.37651711, 58.57561685),
 (12.54839273, 58.57915469),
 (11.58168223, 57.92778293),
 (12.54839273, 58.57915469),
 (13.74565224, 58.77655262),
 (13.01441632, 56.52702944),
 (13.00939974, 56.61638916),
 (13.05845329, 55.72345025),
 (13.37342729, 59.31075839),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (13.04883689, 55.90191767),
 (11.3751847, 58.28082176),
 (18.98735381, 57.73084737),
 (16.40825007, 56.26724457),
 (16.40825007, 56.26724457),
 (16.40825007, 56.26724457),
 (16.40825007, 56.26724457),
 (16.40825007, 56.26724457),
 (13.70188605, 55.46481624),
 (14.95755619, 58.33451576),
 (13.03423239, 56.16973386),
 (13.03423239, 56.16973386),
 (13.04883689, 55.90191767),
 (14.01416648, 55.55719141),
 (14.01416648, 55.55719141),
 (17.88523646, 62.61652736),
 (14.01657909, 55.46798134),
 (14.01657909, 55.46798134),
 (13.70188605, 55.46481624),
 (13.70188605, 55.46481624),
 (12.50336621, 56.87515862),
 (13.01940768, 56.43768387),
 (13.689054500000001, 55.82171965),
 (11.36555324, 58.370326299999995),
 (11.36555324, 58.370326299999995),
 (12.54706353, 56.24981778),
 (13.01940768, 56.43768387),
 (13.01441632, 56.52702944),
 (12.54706353, 56.24981778),
 (12.54706353, 56.24981778),
 (12.39739557, 58.30685634),
 (13.08977324, 58.14027239),
 (18.49389067, 57.83589965),
 (12.54706353, 56.24981778),
 (13.21688093, 55.72603494),
 (18.48477544, 57.74645121),
 (18.48477544, 57.74645121),
 (12.56790607, 58.31036482),
 (11.90251948, 58.11584961),
 (11.90251948, 58.11584961),
 (14.32967864, 55.55948943),
 (13.21247556, 55.8152677),
 (12.23425754, 58.21355399),
 (14.32135336, 56.00581045),
 (18.59607092, 57.20511401),
 (18.59607092, 57.20511401),
 (11.31661871, 58.81799182),
 (12.89486212, 55.80986429),
 (12.89486212, 55.80986429),
 (12.88964933, 55.89909833),
 (12.88964933, 55.89909833),
 (12.88964933, 55.89909833),
 (12.89486212, 55.80986429),
 (12.88964933, 55.89909833),
 (12.89486212, 55.80986429),
 (12.88964933, 55.89909833),
 (12.89486212, 55.80986429),
 (12.89486212, 55.80986429),
 (12.89486212, 55.80986429),
 (18.09937468, 62.79201151),
 (11.33634963, 58.63889782),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (15.47111542, 58.4232731),
 (14.17394423, 55.46923648),
 (14.17394423, 55.46923648),
 (11.55457226, 58.19624524),
 (13.42510483, 58.23472757),
 (17.90288347, 62.79620715),
 (13.00939974, 56.61638916),
 (18.24932033, 57.03591504),
 (12.72485453, 55.98529944),
 (13.21247556, 55.8152677),
 (13.21247556, 55.8152677),
 (11.32651064, 58.72844032),
 (11.32651064, 58.72844032),
 (11.32651064, 58.72844032),
 (11.32651064, 58.72844032),
 (11.32651064, 58.72844032),
 (11.32651064, 58.72844032),
 (13.05365697, 55.81267617),
 (14.01416648, 55.55719141),
 (14.280232199999999, 58.06349568),
 (15.29989478, 58.4238106),
 (13.01441632, 56.52702944),
 (11.36555324, 58.370326299999995),
 (11.58168223, 57.92778293),
 (14.95744317, 58.42416941),
 (17.65756551, 62.2610244),
 (13.01940768, 56.43768387),
 (13.39119136, 55.37160352),
 (14.16577752, 55.82618681),
 (13.00939974, 56.61638916),
 (13.01441632, 56.52702944),
 (13.01441632, 56.52702944),
 (13.01441632, 56.52702944),
 (13.39119136, 55.37160352),
 (18.642849899999998, 57.65205918),
 (18.11694324, 57.39790804),
 (18.66190367, 57.83091768),
 (18.66190367, 57.83091768),
 (18.66190367, 57.83091768),
 (18.24932033, 57.03591504),
 (18.81987884, 57.73628155),
 (12.49699639, 56.96454775),
 (18.82887408, 63.85508948),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (21.62225509, 65.2910375),
 (15.82898422, 59.04928668),
 (17.10958465, 57.24084081),
 (17.10958465, 57.24084081),
 (17.10958465, 57.24084081),
 (17.10958465, 57.24084081),
 (17.10958465, 57.24084081),
 (14.44229137, 58.51257772),
 (14.44229137, 58.51257772),
 (14.44229137, 58.51257772),
 (21.62225509, 65.2910375),
 (18.08506897, 57.04032015),
 (13.01441632, 56.52702944),
 (18.08506897, 57.04032015),
 (18.08506897, 57.04032015),
 (18.08506897, 57.04032015),
 (18.08506897, 57.04032015),
 (13.01441632, 56.52702944),
 (13.01441632, 56.52702944),
 (13.00939974, 56.61638916),
 (13.01940768, 56.43768387),
 (13.01441632, 56.52702944),
 (13.23428746, 55.36926346),
 (13.01441632, 56.52702944),
 (13.01441632, 56.52702944),
 (13.01940768, 56.43768387),
 (12.45148145, 57.59062891),
 (11.32651064, 58.72844032),
 (11.32651064, 58.72844032),
 (13.01441632, 56.52702944),
 (13.42926349, 58.14512344),
 (14.78621707, 58.4239907),
 (14.10848788, 58.15198675),
 (13.85922574, 55.46650792),
 (13.85922574, 55.46650792),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (13.01940768, 56.43768387),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (13.01940768, 56.43768387),
 (14.17603937, 62.37405933),
 (14.95755619, 58.33451576),
 (18.09297631, 57.12969841),
 (18.09297631, 57.12969841),
 (18.22987453, 67.55647713),
 (11.7157435, 58.29044862),
 (14.17603937, 62.37405933),
 (13.85361498, 55.6449365),
 (13.01441632, 56.52702944),
 (13.01940768, 56.43768387),
 (12.54181855, 58.66877112),
 (13.544561900000001, 55.46290634),
 (13.70188605, 55.46481624),
 (13.70188605, 55.46481624),
 (13.544561900000001, 55.46290634),
 (14.01174199, 55.64641771),
 (13.01940768, 56.43768387),
 (13.21247556, 55.8152677),
 (13.21247556, 55.8152677),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (16.4153324, 56.44593652),
 (17.09513621, 59.75293828),
 (12.73243384, 58.40323137),
 (13.76884134, 58.14902834),
 (11.60836929, 57.65941794),
 (13.20804837, 55.90451607),
 (13.01441632, 56.52702944),
 (13.04883689, 55.90191767),
 (13.70188605, 55.46481624),
 (13.70188605, 55.46481624),
 (14.15305142, 63.18336779),
 (18.24932033, 57.03591504),
 (18.24932033, 57.03591504),
 (18.24932033, 57.03591504),
 (18.24932033, 57.03591504),
 (13.05845329, 55.72345025),
 (13.07740459, 55.36670587),
 (13.07740459, 55.36670587),
 (13.07740459, 55.36670587),
 (13.07740459, 55.36670587),
 (13.07740459, 55.36670587),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (18.98735381, 57.73084737),
 (14.95732955, 58.51383352),
 (14.95732955, 58.51383352),
 (18.98735381, 57.73084737),
 (14.95732955, 58.51383352),
 (13.40824765, 58.59324960000001),
 (14.32135336, 56.00581045),
 (14.32135336, 56.00581045),
 (13.21247556, 55.8152677),
 (13.21247556, 55.8152677),
 (14.95744317, 58.42416941),
 (13.58785502, 58.41605608),
 (13.21247556, 55.8152677),
 (12.49699639, 56.96454775),
 (13.70188605, 55.46481624),
 (13.70188605, 55.46481624),
 (18.11694324, 57.39790804),
 (13.21247556, 55.8152677),
 (13.21247556, 55.8152677),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.01441632, 56.52702944),
 (18.66190367, 57.83091768),
 (18.66190367, 57.83091768),
 (14.61703341, 58.24427963),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (19.58494598, 63.47263311),
 (14.16371055, 55.91546415),
 (13.01441632, 56.52702944),
 (15.48136918, 59.14084266),
 (13.01441632, 56.52702944),
 (11.3751847, 58.28082176),
 (12.90902735, 58.31666907),
 (11.3751847, 58.28082176),
 (13.21688093, 55.72603494),
 (18.24932033, 57.03591504),
 (13.00939974, 56.61638916),
 (12.86853754, 56.25618642),
 (14.7867848, 58.33433755),
 (14.7867848, 58.33433755),
 (14.7867848, 58.33433755),
 (18.47570761, 57.65701394),
 (18.47570761, 57.65701394),
 (15.92327559, 56.18277189),
 (18.24932033, 57.03591504),
 (14.79956001, 56.18628686),
 (14.79956001, 56.18628686),
 (14.79956001, 56.18628686),
 (18.24932033, 57.03591504),
 (18.24932033, 57.03591504),
 (12.87385498, 56.16689196),
 (12.87385498, 56.16689196),
 (12.91883065, 63.71054299),
 (14.16371055, 55.91546415),
 (17.43524204, 61.9051832),
 (13.22126465, 55.63681795),
 (17.43524204, 61.9051832),
 (17.43524204, 61.9051832),
 (17.43524204, 61.9051832),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.20804837, 55.90451607),
 (11.47060206, 59.00216415),
 (13.07963334, 58.3194647),
 (19.15706378, 63.30540375),
 (19.15706378, 63.30540375),
 (19.15706378, 63.30540375),
 (19.15706378, 63.30540375),
 (19.15706378, 63.30540375),
 (19.15706378, 63.30540375),
 (13.01441632, 56.52702944),
 (19.15706378, 63.30540375),
 (19.15706378, 63.30540375),
 (18.94497973, 63.22131254),
 (14.04274997, 60.4851976),
 (13.95373278, 63.18204398),
 (16.59301801, 56.80139018),
 (14.73375584, 65.07376589),
 (14.73375584, 65.07376589),
 (14.73375584, 65.07376589),
 (13.37533023, 55.72839979),
 (13.37533023, 55.72839979),
 (13.37533023, 55.72839979),
 (13.37533023, 55.72839979),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (18.82986664, 57.82570208),
 (13.38725518, 55.46077826),
 (13.38725518, 55.46077826),
 (13.38725518, 55.46077826),
 (12.6962644, 56.43172994),
 (14.7867848, 58.33433755),
 (13.01441632, 56.52702944),
 (13.06422013, 58.58833077),
 (13.21688093, 55.72603494),
 (13.70188605, 55.46481624),
 (13.21688093, 55.72603494),
 (13.01940768, 56.43768387),
 (14.7867848, 58.33433755),
 (13.07963334, 58.3194647),
 (18.94497973, 63.22131254),
 (20.17783276, 67.86735286),
 (20.17783276, 67.86735286),
 (20.17783276, 67.86735286),
 (20.17783276, 67.86735286),
 (20.17783276, 67.86735286),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.07963334, 58.3194647),
 (15.12832819, 58.33445589),
 (20.17783276, 67.86735286),
 (18.94497973, 63.22131254),
 (11.89432809, 58.20537272),
 (14.95639827, 59.23150019),
 (18.24932033, 57.03591504),
 (12.88441068, 55.98834774),
 (13.70188605, 55.46481624),
 (13.70188605, 55.46481624),
 (15.13291698, 59.50071246),
 (14.61703341, 58.24427963),
 (13.03912478, 56.08044669),
 (16.75630257, 56.79906123),
 (16.76526906, 56.97789799),
 (16.76526906, 56.97789799),
 (13.7918801, 62.28130251),
 (16.76526906, 56.97789799),
 (16.76526906, 56.97789799),
 (16.76077441, 56.88847288),
 (16.58898212, 56.71198593),
 (16.58898212, 56.71198593),
 (16.58898212, 56.71198593),
 (14.95755619, 58.33451576),
 (14.01416648, 55.55719141),
 (13.70188605, 55.46481624),
 (13.60273257, 58.05759526),
 (14.16371055, 55.91546415),
 (14.01416648, 55.55719141),
 (14.01416648, 55.55719141),
 (14.95755619, 58.33451576),
 (13.06422013, 58.58833077),
 (12.79691017, 57.41828233),
 (13.02931553, 56.25903589999999),
 (12.56790607, 58.31036482),
 (14.78734953, 58.24469476),
 (14.78621707, 58.4239907),
 (14.78621707, 58.4239907),
 (13.76884134, 58.14902834),
 (13.03797433, 59.03663606),
 (13.85642724, 55.5557141),
 (13.69870177, 55.55401796),
 (13.69870177, 55.55401796),
 (13.69870177, 55.55401796),
 (13.70188605, 55.46481624),
 (13.70188605, 55.46481624),
 (13.04883689, 55.90191767),
 (13.04883689, 55.90191767),
 (13.04883689, 55.90191767),
 (13.75828295, 63.09052638),
 (13.24092795, 58.50127074),
 (14.95755619, 58.33451576),
 (14.14241769, 63.54305697),
 (13.23428746, 55.36926346),
 (14.7867848, 58.33433755),
 (14.7867848, 58.33433755),
 (14.7867848, 58.33433755),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (18.25764726, 57.12528137),
 (12.55493186, 58.48954804),
 (14.15954574, 56.09406531),
 (14.15954574, 56.09406531),
 (13.04883689, 55.90191767),
 (13.04883689, 55.90191767),
 (13.04883689, 55.90191767),
 (18.24932033, 57.03591504),
 (12.88964933, 55.89909833),
 (18.24932033, 57.03591504),
 (12.88964933, 55.89909833),
 (16.74742669, 56.62027909),
 (13.05365697, 55.81267617),
 (13.05365697, 55.81267617),
 (15.65989968, 59.31952974),
 (13.07963334, 58.3194647),
 (16.76077441, 56.88847288),
 (14.17603937, 62.37405933),
 (16.75630257, 56.79906123),
 (14.63992211, 56.09656673),
 (13.07963334, 58.3194647),
 (14.16371055, 55.91546415),
 (14.16371055, 55.91546415),
 (14.16371055, 55.91546415),
 (14.16371055, 55.91546415),
 (14.16371055, 55.91546415),
 (12.99929017, 56.79515033),
 (18.25764726, 57.12528137),
 (14.13700006, 63.72289406),
 (14.01416648, 55.55719141),
 (13.59904264, 58.14719419),
 (13.85922574, 55.46650792),
 (13.85922574, 55.46650792),
 (13.07452294, 58.40907651),
 (13.07452294, 58.40907651),
 (13.41249568, 58.50360376),
 (12.90902735, 58.31666907),
 (12.90902735, 58.31666907),
 (12.90902735, 58.31666907),
 (12.90902735, 58.31666907),
 (12.90902735, 58.31666907),
 (12.56790607, 58.31036482),
 (11.32651064, 58.72844032),
 (12.73845079, 58.31363575),
 (13.24092795, 58.50127074),
 (13.39119136, 55.37160352),
 (13.41249568, 58.50360376),
 (15.30642209, 59.14139233),
 (13.77208427, 58.05942436),
 (13.77208427, 58.05942436),
 (21.24163539, 64.58457172),
 (21.24163539, 64.58457172),
 (21.24163539, 64.58457172),
 (12.73243384, 58.40323137),
 (13.43340025, 58.05553023),
 (13.43340025, 58.05553023),
 (13.58785502, 58.41605608),
 (16.74358667, 59.84805505),
 (14.95755619, 58.33451576),
 (12.49699639, 56.96454775),
 (14.95755619, 58.33451576),
 (14.7867848, 58.33433755),
 (14.95744317, 58.42416941),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (12.49699639, 56.96454775),
 (14.95744317, 58.42416941),
 (14.95744317, 58.42416941),
 (15.12901342, 58.51377332),
 (14.95755619, 58.33451576),
 (14.7867848, 58.33433755),
 (12.78581316, 62.80873809),
 (12.49699639, 56.96454775),
 (11.53625899, 58.37527191),
 (12.90902735, 58.31666907),
 (14.63992211, 56.09656673),
 (14.63992211, 56.09656673),
 (14.10375334, 58.3312441),
 (18.24932033, 57.03591504),
 (13.41672109, 58.41396805),
 (13.04883689, 55.90191767),
 (14.14510108, 63.45313621),
 (14.14510108, 63.45313621),
 (14.14510108, 63.45313621),
 (14.14510108, 63.45313621),
 (14.14510108, 63.45313621),
 (14.14510108, 63.45313621),
 (14.14510108, 63.45313621),
 (13.04883689, 55.90191767),
 (16.93430064, 57.06475966),
 (13.58785502, 58.41605608),
 (15.12901342, 58.51377332),
 (13.01441632, 56.52702944),
 (13.01441632, 56.52702944),
 (13.01441632, 56.52702944),
 (16.0892139, 56.36005881),
 (13.59533319, 58.23680404),
 (13.77208427, 58.05942436),
 (13.77208427, 58.05942436),
 (15.48136918, 59.14084266),
 (17.65150001, 60.01222644),
 (12.39739557, 58.30685634),
 (14.95744317, 58.42416941),
 (14.95744317, 58.42416941),
 (13.53017627, 55.81978948),
 (13.53017627, 55.81978948),
 (13.53017627, 55.81978948),
 (13.53017627, 55.81978948),
 (13.53017627, 55.81978948),
 (13.53017627, 55.81978948),
 (14.95918218, 56.99109459),
 (13.53017627, 55.81978948),
 (13.41249568, 58.50360376),
 (14.01657909, 55.46798134),
 (14.01657909, 55.46798134),
 (13.25026639, 58.322022600000004),
 (14.09655651, 58.60020884),
 (12.54839273, 58.57915469),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.37131597, 55.81763882),
 (13.41249568, 58.50360376),
 (13.41672109, 58.41396805),
 (12.73243384, 58.40323137),
 (16.09195318, 56.449421400000006),
 (11.31661871, 58.81799182),
 (14.61703341, 58.24427963),
 (11.31661871, 58.81799182),
 (14.95755619, 58.33451576),
 (16.76077441, 56.88847288),
 (16.76077441, 56.88847288),
 (14.04274997, 60.4851976),
 (14.04274997, 60.4851976),
 (15.29989478, 58.4238106),
 (15.29989478, 58.4238106),
 (15.29989478, 58.4238106),
 (12.90902735, 58.31666907),
 (13.41249568, 58.50360376),
 (13.25489854, 58.2324139),
 (13.08471671, 58.22986308),
 (14.95800232, 57.97600933),
 (14.09413182, 58.68988409),
 (14.17394423, 55.46923648),
 (13.24560959, 58.41164151),
 (13.58785502, 58.41605608),
 (18.67660376, 59.53728426),
 (12.92006686, 58.13749219),
 (14.27833099, 58.15311093),
 (12.03288079, 58.567822899999996),
 (14.95698502, 58.78288675),
 (13.76884134, 58.14902834),
 (12.37651711, 58.57561685),
 (13.21247556, 55.8152677),
 (14.10848788, 58.15198675),
 (12.71350402, 56.16382741),
 (14.10375334, 58.3312441),
 (14.10375334, 58.3312441),
 (14.10375334, 58.3312441),
 (23.40563839, 66.83367579),
 (23.40563839, 66.83367579),
 (23.40563839, 66.83367579),
 (23.40563839, 66.83367579),
 (23.40563839, 66.83367579),
 (23.40563839, 66.83367579),
 (23.40563839, 66.83367579),
 (12.81917865, 62.35935271),
 (13.20128548, 62.45480179),
 (12.91456172, 58.22707518),
 (13.41249568, 58.50360376),
 (13.41249568, 58.50360376),
 (13.20128548, 62.45480179),
 (13.07963334, 58.3194647),
 (13.20128548, 62.45480179),
 (13.41249568, 58.50360376),
 (13.20128548, 62.45480179),
 (12.59344597, 57.95212385),
 (13.20128548, 62.45480179),
 (14.7867848, 58.33433755),
 (14.7867848, 58.33433755),
 (13.24560959, 58.41164151),
 (16.26638936, 56.80536692),
 (14.15744774, 56.18338877),
 (12.37651711, 58.57561685),
 (13.99943848, 56.09278670000001),
 (13.23428746, 55.36926346),
 (12.54839273, 58.57915469),
 (15.29989478, 58.4238106),
 (13.77208427, 58.05942436),
 (12.54839273, 58.57915469),
 (16.41178235, 56.35658324),
 (14.62497958, 57.52755482),
 (14.955175400000002, 60.12935699999999),
 (14.955175400000002, 60.12935699999999),
 (14.955175400000002, 60.12935699999999),
 (14.955175400000002, 60.12935699999999),
 (14.955175400000002, 60.12935699999999),
 (11.51775022, 58.55433768),

In [ ]:
longitude, latitude = [list(tup) for tup in zip(*coordinates)]

In [ ]:
coordinates_NWP = pd.DataFrame(data=list(zip(longitude,latitude)),columns=['longitude', 'latitude'])

In [ ]:
coordinates_NWP.to_csv('Turbine_NWP_coordinates.csv')

In [ ]:
from google.colab import files
files.download('Turbine_NWP_coordinates.csv')